# docker-compose.yml
version: '3'
services:
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025" #smtp
            - "8025:8025"
        networks:
            - web
        
networks:
  web:
    driver: bridge
