# docker-compose.yml
---
version: '3'
services:
    # zookeeper:
    #     image: confluentinc/cp-zookeeper:5.3.0
    #     hostname: zookeeper
    #     container_name: zookeeper
    #     ports:
    #         - "2181:2181"
    #     environment:
    #         ZOOKEEPER_CLIENT_PORT: 2181
    #         ZOOKEEPER_TICK_TIME: 2000
    #     networks:
    #         back-tier:
    # kafka:
    #     image: confluentinc/cp-enterprise-kafka:5.3.0
    #     ports:
    #         - "29092:29092"
    #         - "9092:9092"
    #     depends_on:
    #         - zookeeper
    #     environment:
    #         KAFKA_BROKER_ID: 1
    #         KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    #         KAFKA_CREATE_TOPICS: "test:1:1"
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    #         KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #         KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    #         CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
    #         CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
    #         CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
    #         CONFLUENT_METRICS_ENABLE: 'true'
    #         CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     networks:
    #         back-tier:
    ui:
        image: landoop/kafka-topics-ui
        ports:
            - "8000:8000"
        depends_on:
            - rest-proxy
        environment:
            KAFKA_REST_PROXY_URL: rest-proxy:8082
            PROXY: "true"
        networks:
            back-tier:
    schema-registry:
        image: confluentinc/cp-schema-registry:5.3.0
        hostname: schema-registry
        container_name: schema-registry
        depends_on:
            - kafka
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
        networks:
            back-tier:
    rest-proxy:
        image: confluentinc/cp-kafka-rest:5.3.0
        depends_on:
            - kafka
            - schema-registry
        ports:
            - 8082:8082
        hostname: rest-proxy
        container_name: rest-proxy
        environment:
            KAFKA_REST_HOST_NAME: rest-proxy
            KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:29092'
            KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
            KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
        networks:
            back-tier:
        
networks:
  back-tier:
